### ISSUE TITLE
trouble building

### ISSUE THREAD

**Issue by ivanixgames** [heipei/nginx-sso#1]
Hello,
I am really interested in trying out this software. looks like it could be a great way to authen/authorize webapps composed of static web and websockets all at one go!
However, i'm having trouble buidling.  the error i see is:
$ make
go build ssoauth.go
ssoauth.go:30:2: cannot find package "github.com/Sirupsen/logrus" in any of:
	/usr/lib/go/src/pkg/github.com/Sirupsen/logrus (from $GOROOT)
	($GOPATH not set)
ssoauth.go:31:2: cannot find package "github.com/heipei/nginx-sso/ssocookie" in any of:
	/usr/lib/go/src/pkg/github.com/heipei/nginx-sso/ssocookie (from $GOROOT)
	($GOPATH not set)
make: *** [ssoauth] Error 1

**Comment by heipei** [comment]
Hey @ivanixgames ,

make sure you understand how to set up your Go environment locally (with $GOPATH) etc. Refer to this: http://www.zhubert.com/blog/2014/02/11/setting-up-go/

Then, in the nginx-sso folder do this:
`go get ./...`
Then call make.
Let me know how it works out!
